debug: true
app_env: 'dev'
database:
  host: 'localhost'
  dbname: 'mining'
  user: 'postgres'
  password: 'postgres'
  port: 5432
server:
  address: 'localhost:3000'
rabbit:
  host: 'localhost'
  port: 5672
  vhost: /
  user: guest
  password: guest
  persisted: true
  stream: true